### PR TITLE
Add new game

### PR DESCRIPTION
**Pull request by virejdasani**
Added the infamous Pong game, I used python and turtle to make it.

I made this a while back: https://github.com/virejdasani/PongGame

Proof:

image

### CODE REVIEW

**Review by pralinkhaira1903 — COMMENTED** [review]
# Review
- No Description added.
- Adding Description is req just to ensure that even if i merge this then hacktober fest should not reject this!!
- Add description then i will merge.
- Moreover I want to check the authenticity of this code, any proof that you made it since you used `Pong by Virej Dasani`

**Review by pralinkhaira1903 — APPROVED** [review]
# Review
- Nice Job Buddy!!
- Satisfied with description and other factors.
- Happy Coding/Contributing :)
- Follow My [LinkedIn](https://www.linkedin.com/in/pralin-khaira-bb462a252/)

**Comment by pralinkhaira1903** [comment]
> Added the infamous Pong game, I used python and turtle to make it.
> 
> I made this a while back: https://github.com/virejdasani/PongGame
> 
> Proof:
> 
> image

Arrey, gottcha, Thanks!!

**Comment by pralinkhaira1903** [comment]
How many more PR do you need??

**Comment by virejdasani** [comment]
> How many more PR do you need??

I need 1 more

**Pull request merged**
