### PR TITLE
question realted to finding pair in unsorted array

### PR DESCRIPTION
**Pull request by Ocidemus**
finding pair in unsorted array which has difference of x

### CODE REVIEW

**Review by pralinkhaira1903 — CHANGES_REQUESTED** [review]
# Review
- As far as I know `Elements contain diff x ` is completely different question from `Boundary Transversal of matrix`, so why have you put it in subfolder?
- Correct path should be `Geeks For Geeks Solutions/elements contain diff x/elements contain diff x.cpp` instead of `Geeks For Geeks Solutions/Boundary traversal of matrix/questions/elements contain diff x.cpp`.
- Also star the repo!!

**Review by pralinkhaira1903 — APPROVED** [review]
# Review
- Nice Job Buddy!!
- Share and Star the repo!!
- Happy Coding/Contributing :)

**Review by pralinkhaira1903 — APPROVED** [review]

**Review by pralinkhaira1903 — APPROVED** [review]
# Review
- Nice Job Buddy!!
- Share and Star the repo!!
- Happy Coding/Contributing :)

**Comment by Ocidemus** [comment]
thanks mate : )
took me a while to learn coz i am new here but we ball : )

**Comment by pralinkhaira1903** [comment]
> thanks mate : ) took me a while to learn coz i am new here but we ball : )

- Open source means learning, so feel free to comment and ask for help whereever required
- Happy Coding/Contributing :)
- Moreover I recommend you making all the other 3 PR here only, easier for you!!

**Pull request merged**
