### PR TITLE
Make program to check odd or even number

### PR DESCRIPTION
**Pull request by Noklent-Fardian**
program for check odd or even number

### CODE REVIEW

**Comment by pralinkhaira1903** [comment]
Description Required!!!

**Comment by Noklent-Fardian** [comment]
> Description Required!!!
okay

**Comment by pralinkhaira1903** [comment]
> > Description Required!!!
> > okay

- It's req just to ensure that even if i merge this then hacktober fest should not reject this!!
- Happy Coding/Contributing :)

**Review by pralinkhaira1903 — APPROVED** [review]
# Review
- Nice Job Buddy!!
- Share and Star the repo!!

**Pull request merged**
