### PR TITLE
added myself and java code

### PR DESCRIPTION
**Pull request by CrazyRikin**
hey i am rikin and i have added a java program which converts integer number to binary number !

### CODE REVIEW

**Comment by pralinkhaira1903** [comment]
Description Required!!!

**Comment by CrazyRikin** [comment]
> Description Required!!!

added please check.

**Comment by pralinkhaira1903** [comment]
> > Description Required!!!
> 
> added please check.


- Adding Description is req just to ensure that even if i merge this then hacktober fest should not reject this!!
- Happy Coding/Contributing :)

**Comment by CrazyRikin** [comment]
> > > Description Required!!!
> > 
> > 
> > added please check.
> 
> * Adding Description is req just to ensure that even if i merge this then hacktober fest should not reject this!!
> * Happy Coding/Contributing :)
> * Star and Share repo!!

thank you for your help .

**Comment by pralinkhaira1903** [comment]
> > > > Description Required!!!
> > > 
> > > 
> > > added please check.
> > 
> > 
> > 
> > * Adding Description is req just to ensure that even if i merge this then hacktober fest should not reject this!!
> > * Happy Coding/Contributing :)
> > * Star and Share repo!!
> 
> thank you for your help . do share your LinkedIn profile lets connect there.

- Ayooo Love to connect buddy
- [Linkedin](https://www.linkedin.com/in/pralin-khaira-bb462a252/)

**Pull request merged**
