### PR TITLE
Created Password Generator file

### PR DESCRIPTION
**Pull request by InvisiblePro**
# Pull Request: Password Generator in python

## Description
A Python Program for the users to generate strong passwords.

## Changes Made
- Added a Python script for generating passwords.

## Requirements 
- Compatible with python without any modules

## Usage
- Run the script and follow steps as output suggests.

### CODE REVIEW

**Comment by InvisiblePro** [comment]
Thank you for being attentive to my project.

**Comment by InvisiblePro** [comment]
@pralinkhaira1903, Respected Repository Owner, I am kind to inform you that your repository has been excluded from the Hacktoberfest 2023 recognition.
image

**Comment by pralinkhaira1903** [comment]
> @pralinkhaira1903, Respected Repository Owner, I am kind to inform you that your repository has been excluded from the Hacktoberfest 2023 recognition. image

Well thats sad, IDK why, but anyway thaks for informing!!

**Comment by pralinkhaira1903** [comment]
Just wanted to ask, did same happened with this one?
- [This](https://github.com/InvisiblePro/Hacktoberfest-2022)

**Comment by InvisiblePro** [comment]
@pralinkhaira1903 
Well yea, last year my repo too was excluded.
It is because, hacktoberfest event is to contribute to open-source projects. If you repo is named/titled as Hacktoberfest, then it is clearly aimed for hacktoberfest, so they exclude it; Repo should not be named as 'Hacktoberfest'. You can either name it as any project topics so it seems like you are working on a genuine project with open-source contribution. 

Well, thanks for the profile appreciation! , and yeah, from next time never name repo as "hacktoberfest" in future.
All the best for future and see ya again in next Hacktoberfest too!

**Comment by InvisiblePro** [comment]
Well still time is left, you can create a new repo, and i too could contribute in it! ✨

**Comment by pralinkhaira1903** [comment]
> Well still time is left, you can create a new repo, and i too could contribute in it! ✨ Follow and Star it! 😄 ✨

Hopping in brother!!!!
Btw, can we connect anywhere for direct chat/whatever?

**Comment by InvisiblePro** [comment]
discord(not_darkevil)? or in my official email(hacker.invisiblepro@proton.me)?

**Comment by InvisiblePro** [comment]
> @pralinkhaira1903 Well yea, last year my repo too was excluded. It is because, hacktoberfest event is to contribute to open-source projects. If you repo is named/titled as Hacktoberfest, then it is clearly aimed for hacktoberfest, so they exclude it; Repo should not be named as 'Hacktoberfest'. You can either name it as any project topics so it seems like you are working on a genuine project with open-source contribution.
> 
> Well, thanks for the profile appreciation! , and yeah, from next time never name repo as "hacktoberfest" in future. All the best for future and see ya again in next Hacktoberfest too!
> 
> That's why this time I have named my repo as "CV_Projects" so hacktoberfest authorities could not exclude it, you can check it out! [InvisiblePro/CV_Projects](https://github.com/InvisiblePro/CV_Projects)

Soo next time keep this in mind 😊

**Comment by pralinkhaira1903** [comment]
> not_darkevil

Discord done!!!
Yeah i will keep that in mind

**Pull request merged**
