### PR TITLE
Update Contributers.md

### PR DESCRIPTION
**Pull request by Praweshkafle**
updated successfully

### CODE REVIEW

**Review by pralinkhaira1903 — APPROVED** [review]
- Adding Description is req just to ensure that even if i merge this then hacktober fest should not reject this!!
- Happy Coding/Contributing :)
- Star and Share repo!!

**Comment by Praweshkafle** [comment]
is it okey now?

**Comment by pralinkhaira1903** [comment]
Man Seriously??
At least add something like

- Added my name to `Contributers.md`
- Successfully done my 1st PR.

**Comment by Praweshkafle** [comment]
i am new to the hacktoberfest so should i make another req in another repo or what

**Comment by pralinkhaira1903** [comment]
You can make another pull request here only if you want, contribute to some code, rest you need 3 more PR.

**Pull request merged**
