### PR TITLE
Added new Game

### PR DESCRIPTION
**Pull request by virejdasani**
Added snake game

### CODE REVIEW

**Review by pralinkhaira1903 — APPROVED** [review]
# Review
- Nice Job Buddy!!
- I renamed Game's file to make it look more sensible :)
- Share and Star the repo!!
- Happy Coding/Contributing :)
- Follow My [LinkedIn](https://www.linkedin.com/in/pralin-khaira-bb462a252/)

**Comment by virejdasani** [comment]
Hello, thank you for merging, my hacktoberfest is not accepting this PR because the label is `hacktober-fest-accepted` but it should be `hacktoberfest-accepted`.
Could you please change the label, thank you!

**Comment by pralinkhaira1903** [comment]
> Hello, thank you for merging, my hacktoberfest is not accepting this PR because the label is `hacktober-fest-accepted` but it should be `hacktoberfest-accepted`. Could you please change the label, thank you!

- Now Happy? ;)

**Comment by virejdasani** [comment]
Thank you very much!!

**Pull request merged**
